name: ca-dev
channels:
  - conda-forge
dependencies:
  - gcc
  - gfortran # Compilers
  - waf
  - libmed==4.1.0 # code aster dependencies
  - scotch
  - metis
  - mumps-include
  - mumps-mpi
  - mumps-seq
  - petsc
  - hdf5
  - numpy
  - glib
  - boost