name: ca-dev
channels:
  - krande
  - conda-forge
dependencies:
  - gcc==8.5.0
  - cxx-compiler
  - gfortran==8.5.0 # Compilers
  - waf
  - libmed==4.1.1 # code aster dependencies
  - asrun
  - scotch
  - metis
  - mumps-include
  - mumps-mpi
  - mumps-seq
  - petsc
  - numpy
  - glib
  - boost