{% set name = "code-aster" %}
{% set version = "15.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/codeaster/src
  tag: {{ version }}

build:
  number: 0
  script: ../build.sh

requirements:
  host:
    - gcc
    - gfortran
    - waf
  build:
    - libmed==4.1.0 # code aster dependencies
    - scotch
    - metis
    - mumps-include
    - mumps-mpi
    - mumps-seq
    - petsc
    - hdf5
    - numpy
    - glib
    - boost
  run:
    - libmed==4.1.0 # code aster dependencies
    - scotch
    - metis
    - mumps-include
    - mumps-mpi
    - mumps-seq
    - petsc
    - hdf5
    - numpy
    - glib
    - boost

about:
  home: https://github.com/krande/fe-solvers-compilation
  license: ""
  license_family:
  summary: ""

extra:
  recipe-maintainers:
    - Krande
